Update 5_Organizational_Agreements.md
International-Data-Spaces-Association/IDSA-Rulebook pull request #10
Opened 2023-03-07 11:16 UTC by ssteinbuss

Adding current text for running data space instances

2024-02-28 15:51 UTC, PeterKoen-MSFT requested changes
Critical aspects on interoperability being based on participants interacting in multiple dataspaces is missing.
This text assumes that "European" dataspaces are the global norm and is missing the international aspect of interoperability.
Several factual errors in describing interoperability that need to be fixed before this can become a statement with normative character in the IDSA rulebook.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +It must be recognized that the role of IDS and IDSA is to fulfill
fulfill - what? I can't make sense of this intro paragraph

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +2. the ambition of a federation of interoperable data spaces.
Federation of dataspaces is not a good term. Interoperability happens on 4 levels: technical, semantic, business or legal. A federation of dataspaces could exist on the legal level, be enabled by the business level and supported with common semantics by the semantic level. At technical level no such thing as a federation of dataspaces exists.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +IDS can provide a gradual migration path within a data space instance or
What is being referenced as IDS? The protocol is DSP, the organization is IDSA. There is no IDS meaning that is intuitive at this level.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +pave the way for the federation of interoperable data spaces - as
I disagree with a path towards federation of data spaces as a general term. There can be federations of related data spaces, but not a generic global federation of data spaces.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +pursued by the European data strategy.
"pursed for example by the European..."
The Rulebook needs to consider a global/international view point. the European strategy is just one example of data spaces and also it is only considering the political/legal level of interoperability.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +governance authority.
again, this is for a very specific European data space project and as such only an example.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +with all data space specific authorities.'
This is just an example of one political ask towards data spaces. This can be built with data spaces that are following this rulebook, but it is not the rule for all global dataspace. so it needs to be treated as an example and not as a normative statement.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +As noted above, IDSA and the main IDS-stakeholders play an important
what are IDS-Stakeholders? This is never explained and not a relevant term as IDS is not a defined element. Can we replace this with "IDSA and the international dataspace community"?

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +space interoperability), and embedding them in the European ambition of
again, European is just one example, but we are writing the rulebook for global/international dataspaces

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +Blocks and data space instances](media/media/image18.png)
This picture is outdated and in conflict with other parts of the IDSA Rulebook and should therefore not be used.
Also it is an IPR issue to re-use images from other publications in the IDSA Rulebook.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +framework in relation to the broadly used data sharing agreement
which "broadly used data sharing agreement framework" is referenced here? I'm not aware of one that would be aligned with the IDSA Rulebook.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +- *Intra data space interoperability,* between the data space
missing participants as the core element of interoperability in intra & inter dataspace interop

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +- *Inter data space interoperability,* between multiple data space
Inter DataSpace Interoperability is ONLY about the Legal and Business level. on a technical and semantic layer interoperability is handled by the protocol and the semantic models that the two participants understand. on the Level of Legal and Business Process its about two Dataspace Governance Authorities that need to negotiate equivalency.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +| *Certification* | Validating that stakeholders act according to the standardized way of working. Certification is divided into component certification (certification of technical/software component
It's not Certification, but rather Compliance (with standardized protocols). IDSA will ensure that Certification includes compliance with the protocols, but Certification covers a lot more than interoperability on a technical level.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +| *Operations*           | The operations are about the exploitation and usage of the developed components. The operations can be certified as part of the organizational certification. |
Operations is not a part of interoperability. for two participants to be interoperable on a technical layer they both need to adhere to the protocols, how they manage their IT infrastructure is completely irrelevant for interoperability

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +| *Communication*        | The dissemination of the activity is an important aspect which might include the awareness of the standardization and certification, but also contains marketing aspects. |
again, irrelevant for interoperability on the technical layer. It's the adherence to standardized protocols, definitely not marketing....

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +| *Support*   | The support activities include the structured assistance from stakeholders involved in the operation, development, certification, and communication activities. |
support is not part of interoperability.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +resulting in a federation of interoperable data spaces.
interoperability does not result in a federation of dataspaces. Federations can be created through common legal and business processes and agreements, but they do not exist automatically.

2024-02-28 15:51 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +The federation of data spaces require a common set of reusable standards
Federations (plural) as it is extremely unlikely that there will be one federation of dataspaces to govern them all.

2024-07-03 07:49 UTC, PeterKoen-MSFT commented on documentation/5_Organizational_Agreements.md
> +pave the way for the federation of interoperable data spaces - as
Having thought about this a bit longer I need to change my comment slightly: Technical federation is NOT a path forward for dataspaces. However, dataspace might create Federations at the level of Business Processes or as Legal Entities. This should be clearly distinguished.

2024-08-27 07:14 UTC, ssteinbuss commented
This text is outdated and the relevant content is part of the new section on [Interoperability](https://github.com/International-Data-Spaces-Association/IDSA-Rulebook/blob/main/documentation/3_Interoperability.md). This PR should be rejected and closed.

2024-09-18 13:14 UTC, PeterKoen-MSFT commented
@ssteinbuss I noticed this PR being open for a long time and the comments not being resolved... shall we have another go at trying to resolve the comments together to finally merge the changes?

2024-09-18 13:15 UTC, PeterKoen-MSFT commented
rejected as per @ssteinbuss comments.

2024-09-18 13:15 UTC, closed without merging