update DS Governance Framework
International-Data-Spaces-Association/IDSA-Rulebook pull request #54
Opened 2024-02-27 11:22 UTC by ssteinbuss

First draft of updated sections. Need to integrate the multi level policies aspect.

closes #42

2024-02-27 11:40 UTC, ssteinbuss commented on documentation/2_Guiding_Principles.md
> +regualtions that participants in a data space have to adhere to. It is the core
fix typo

2024-02-27 12:04 UTC, ssteinbuss commented
Participation in the governance framework would make you a participant in the data space, but not as a technical participant, --> discussion on AgriDS and farmers participation in Data Spaces.

2024-02-27 15:18 UTC, PeterKoen-MSFT requested changes

2024-02-27 15:18 UTC, PeterKoen-MSFT commented on documentation/2_Guiding_Principles.md
> +The Data Space Governance Framework is the defined set of policies, rules, and
policies are rules, so this is redundant. Is this rather policies, business process, and regulations... ?

2024-02-27 15:37 UTC, anilturkmayali approved these changes

2024-03-05 11:53 UTC, viivilahteenoja commented on documentation/2_Guiding_Principles.md
> +The Data Space Governance Framework is the defined set of policies, rules, and
DSSC description of "Data space governance framework": "The structured set of principles, processes, and practices that guide and regulate the governance, management and operations within a data space to ensure effective and responsible leadership, control, and oversight. It defines the functionalities the data space provides and the associated data space roles, including the data space governance authority and participants."

2024-03-05 14:34 UTC, PeterKoen-MSFT approved these changes

2024-03-05 14:34 UTC, merged